### Model
model_name_or_path: /path/to/TDAR-8B-Base
train_from_scratch: false
trust_remote_code: true

### Method
stage: sft
do_train: true
finetuning_type: full
freeze_vision_tower: true
freeze_multi_modal_projector: false
freeze_language_model: true
deepspeed: /path/to/ds_z3_config.json
gradient_checkpointing: true

### Dataset
dataset: longcat_sft
template: qwen3  # or qwen2_vl
block_length: 4
cutoff_len: 32768
truncate_mode: drop  # choices: [drop, cut]
overwrite_cache: false
tokenized_path: /cache_dir/for/tokenized_data
preprocessing_num_workers: 96
dataloader_num_workers: 4
neat_packing: true
# streaming: true
# max_steps: 1000

### Output
output_dir: /path/to/your/output/tdar_8b_sft/
logging_steps: 5
save_steps: 512
save_total_limit: 8
plot_loss: true
overwrite_output_dir: false
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### Training
run_name: tdar_8b_longcat_cot_sft
include_effective_tokens_per_second: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: constant_with_warmup
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### Evaluation
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500