model_base: "tdar"
paths:
    dataset_base: "/path/to/dataset"
execute:
    num_chunk: 128
rollout:
    tensor_parallel_size: 1
    max_active: 2
    temperature: 1.0
    max_token: 30000 # max generation token num, current engine is slow for long-cot model
    top_p: 1.0
    top_k: 0
    start_with_think: True # if not reasoning model, set to False, otherwise True
    output_unmasking_history: False
    stop_token_list: ["<|im_end|>"]

    # low_confidence_dynamic
    block_size: 16
    denoising_steps_per_block: 16
    remasking_strategy: "low_confidence_dynamic"
    dynamic_threshold: 0.9

    # bounded_adaptive_confidence_decoding
    # block_size: 16
    # denoising_steps_per_block: 1
    # remasking_strategy: "bounded_adaptive_confidence_decoding"
    # confidence_upper_threshold: 0.9
    # confidence_lower_threshold: 0.6